### Python List Slicing

In [1]:
numbers = [0, 1, 2, 3, 4, 5, 6]
numbers

[0, 1, 2, 3, 4, 5, 6]

In [2]:
numbers[0:3]

[0, 1, 2]

In [3]:
numbers[:3]

[0, 1, 2]

In [4]:
numbers[5:]

[5, 6]

In [5]:
numbers[:]

[0, 1, 2, 3, 4, 5, 6]

In [6]:
numbers[-1]

6

In [7]:
numbers[-3:]

[4, 5, 6]

In [8]:
numbers[3:-2]

[3, 4]

### Numpy

Main data type: np.ndarray

In [9]:
import numpy as np

In [11]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [12]:
x.shape

(3,)

In [14]:
y = np.array([[3, 4, 5], [6, 7, 8]])
y

array([[3, 4, 5],
       [6, 7, 8]])

In [15]:
y.shape

(2, 3)

In [17]:
x1 = np.array([[1], [2], [3]])
x1.shape

(3, 1)

### np.ndarray Operations 操作函数

In [22]:
import pandas as pd

In [18]:
x = np.array([1, 2, 3]) # 一维向量
x.max()

3

In [20]:
y = np.array([[3, 4, 5], [6, 7, 8]])
y

array([[3, 4, 5],
       [6, 7, 8]])

In [21]:
np.max(y, axis=0)

array([6, 7, 8])

#### DataFrame max 注意区分

In [25]:
df = pd.DataFrame(y,columns=['A', 'B', 'C'])
df

A  B  C
0  3  4  5
1  6  7  8

In [26]:
df.max(axis=0)

A    6
B    7
C    8
dtype: int32

In [43]:
type(df.max(axis=0))

pandas.core.series.Series

=============================================

In [27]:
np.max(y, axis=1, keepdims = True)

array([[5],
       [8]])

### np.dot

In [29]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
np.dot(a, b)
#1*1 + 2*2 + 3*3

14

In [34]:
c = a.T * b
print('c: ', c)
print('sum:', sum(c))

c:  [1 4 9]
sum: 14


In [35]:
np.multiply(a,b)

array([1, 4, 9])

### Indexing 索引

In [36]:
# 条件索引
x = np.array([1, 2, 3])
x[x > 2] 

array([3])

In [37]:
index = [2, 1, 0]
x[index]

array([3, 2, 1])

#### 矩阵遍历

In [38]:
y = np.array([[3, 4, 5], [6, 7, 8]]) # 二维矩阵
print(y)

[[3 4 5]
 [6 7 8]]


In [39]:
# 默认按第1维度遍历
for y1 in y:
    print(y1)
    print("————")

[3 4 5]
————
[6 7 8]
————


In [40]:
# 按指定维度遍历
d1, d2 = y.shape
print(d1, d2)

2 3


In [41]:
for d in range(d2):
    print(d, y[:,d])

0 [3 6]
1 [4 7]
2 [5 8]


### Efficient Numpy Code

In [44]:
x = np.array([[3,4,5], [6,7,8]]) #二维矩阵
y = np.array([[1,2,3], [9,0,10]]) #二维矩阵

In [82]:
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        x[i, j] **= 2
x

array([[-1876701183,           0,   689565697],
       [          0,  -359178239,           0]], dtype=int32)

In [83]:
x ** 2
x  # 用numpy内置的函数，会快

array([[-1876701183,           0,   689565697],
       [          0,  -359178239,           0]], dtype=int32)

#### 全0 和全1 的矩阵

In [84]:
z = np.zeros((2))
for i in range(x.shape[0]):
    x1 = x[i]
    y1 = y[i]
    z[i] = np.dot(x1, y1)
z

array([1.91995908e+08, 0.00000000e+00])

In [85]:
z = np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

### 矩阵和常熟计算以及 Broadcasting广播

In [86]:
x = np.array([[3,4,5], [6,7,8], [1,2,3]]) # 二维矩阵
x.shape

(3, 3)

In [87]:
x + 2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 3,  4,  5]])

In [88]:
x * 2

array([[ 6,  8, 10],
       [12, 14, 16],
       [ 2,  4,  6]])

In [90]:
y = np.array([[2], [4], [8]])
y.shape

(3, 1)

In [91]:
x + y

array([[ 5,  6,  7],
       [10, 11, 12],
       [ 9, 10, 11]])

In [96]:
z = np.array([[2, 4, 8]])
z

array([[2, 4, 8]])

In [97]:
z.shape

(1, 3)

In [94]:
z = y.reshape(1, -1)
z.shape

(1, 3)

In [95]:
z = y.T
z.shape

(1, 3)